#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_ABOUTBOX                            103
#define IDM_ABOUT                               104
#define IDM_EXIT                                105
#define IDI_TZT                                 107
#define IDC_TZT                                 109
#define IDD_DRIVER_TWEAKS                       131
#define IDD_TZT                                 135
#define IDI_STEAM                               137
#define IDD_AUDIO                               139
#define IDD_FRAMERATE                           141
#define IDD_STEAM                               143
#define IDD_GRAPHICS                            145
#define IDD_OSD                                 147
#define IDD_PLUGINS                             149
#define IDC_VSYNC                               1000
#define IDC_BORDER_WINDOW                       1001
#define IDC_BORDERLESS_WINDOW                   1002
#define IDC_FULLSCREEN                          1003
#define IDC_MATCH_DESKTOP                       1004
#define IDC_REFRESH_RATE                        1008
#define IDC_ANISOTROPY                          1030
#define IDC_TEXTURE_RES                         1035
#define IDC_LEVEL_OF_DETAIL                     1044
#define IDC_SHADOW_QUALITY                      1045
#define IDC_GPUINFO                             1054
#define IDC_SLI_MODE                            1056
#define IDC_POWER_POLICY                        1057
#define IDC_PRERENDERED_FRAMES                  1058
#define IDC_NV_DRIVER_TWEAKS                    1061
#define IDC_NEGATIVE_LOD                        1063
#define IDC_QUALITY_DESC                        1065
#define IDC_ADAPTIVE_VSYNC                      1066
#define IDC_SMOOTH_VSYNC                        1067
#define IDC_COMBO5                              1068
#define IDC_NUKE_CONFIG                         1069
#define IDC_DEBUG_GROUP                         1070
#define IDC_GPU_GROUP                           1071
#define IDC_BACKUP_CONFIG                       1072
#define IDC_RESTORE_CONFIG                      1073
#define IDC_RESOLUTION                          1074
#define IDC_TZFIX_TABS                          1075
#define IDC_FXAA_LEVEL                          40000
#define IDC_SHIM_MODE                           40000
#define IDC_TZFIX_AUDIO_COMPATIBILITY           40000
#define IDC_TZFIX_FRAMERATE_FAKESLEEP           40000
#define IDC_TZFIX_GRAPHICS_ARC                  40000
#define IDC_TZFIX_STEAM_PLAY_SOUND              40000
#define IDS_APP_TITLE                           40000
#define IDC_DRAW_DISTANCE                       40001
#define IDC_SHIM_APP_OVERRIDE                   40001
#define IDC_TZFIX_AUDIO_CHANNELS                40001
#define IDC_TZFIX_FRAMERATE_MIN_LATENCY         40001
#define IDC_TZFIX_GRAPHICS_FORCE_MIPMAPS        40001
#define IDC_TZFIX_STEAM_TAKE_SCREENSHOT         40001
#define IDC_ASYNC_PRESENT                       40002
#define IDC_TZFIX_AUDIO_RATE                    40002
#define IDC_TZFIX_FUDGE_FACTOR                  40002
#define IDC_TZFIX_GRAPHICS_DISABLE_SCISSOR      40002
#define IDC_TZFIX_STEAM_ALLOW_BROADCASTS        40002
#define IDC_INSTALL_TZFIX                       40003
#define IDC_PRIORITY_INVERSION                  40003
#define IDC_TARGET_FPS                          40003
#define IDC_TZFIX_CHANNEL_LABEL                 40003
#define IDC_TZFIX_GRAPHICS_SHADOW_RES           40003
#define IDC_IGNORE_OEM                          40004
#define IDC_TZFIX_AUDIO_STATUS                  40004
#define IDC_TZFIX_FRAMERATE_ALLOW_WINDOWED      40004
#define IDC_TZFIX_GRAPHICS_POSTPROCESS_SCALE    40004
#define IDC_UNINSTALL_TZFIX                     40004
#define IDC_TZFIX_AUDIO_ENABLE                  40005
#define IDC_TZFIX_FRAMERATE_YIELD               40005
#define IDC_TZFIX_GRAPHICS_DOUBLE_RES_SORREY    40005
#define IDC_TZFIX_RATE_LABEL                    40006
#define IDC_TZFIX_TRIPLE_BUFFERING              40006
#define IDC_TZFIX_FRAMERATE_STUTTER_FIX         40007
#define IDC_TZFIX_PRERENDER_LIMIT               40008
#define IDC_TZFIX_FUDGE_FACTOR_LABEL            40009
